pipeline {
    agent {
  label 'Slave'

    }
    stages {
        stage('CloneRepo'){
            steps {
                git branch: 'main', credentialsId: '68d805e9-0de7-4936-9b22-ad5b45a8bb70', url: 'git@github.com:souzare/HTML.git'
                sh '''
                if [ ! -d /home/ec2-user/html_storage ]; then mkdir /home/ec2-user/html_storage; fi
                cp index.html /home/ec2-user/html_storage'''
                }
        }
        stage('DeployApache'){
            steps {
            sh '''cp /home/ec2-user/html_storage/index.html /var/www/html
            sudo systemctl restart httpd'''
            }
        }
        stage('ExibeLinkDoSite'){
            steps {
            sh '''IP=$(curl ifconfig.me)
            echo Esse é o link do site $IP'''
            }
        }
    }
}
